# version defines the version of the config.yml configuration format. Currently the only option is 1.
version: 1

# module_version defines the version of the module to publish.
module_version: 1.1.0

tests:
  - name: Basic Example
    project_root: test/basic
    before_init:
      # Set random Prefix
      - export TF_VAR_random_prefix=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 8 | head -n 1)
    after_apply:
      # Get the value of our Terraform output
      - RESULT=$(terraform output -raw lambda_result)
      # Check it's in our set of custom outcomes
      - echo "success" | grep "$RESULT"