name: Test
on: pull_request_target

jobs:
  test:
    permissions:
      id-token: write
      contents: read
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terratest Test Runner
        uses: cloudposse/github-action-terratest@1.0.0
        with:
          sourceDir: test/
